### ISSUE TITLE
Halaman Computed Properties and Watchers

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#10]

**Comment by iqbalaqaba** [comment]
Mas @mazipan  & @nusendra , saya assign yang ini juga ya 😄

**Comment by mazipan** [comment]
Kita review yang pertama dulu mas @iqbalaqaba 
Sampai bisa di merge baru ambil lagi.
Takut nanti overload, sementara yang pertama belum di merge

**Comment by iqbalaqaba** [comment]
mas @mazipan dan mas @nusendra , yang pertama sudah di merge, apakah boleh di assign untuk yang ini kepada saya ?

**Comment by mazipan** [comment]
Silahkan mas @iqbalaqaba

**Comment by iqbalaqaba** [comment]
siap

**Comment by iqbalaqaba** [comment]
Hasil translate bahasa indonesia dari Vue Computed Property & Watcher ada di PR #59 😉
