### ISSUE TITLE
[API] - Options / Assets

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#107]

**Comment by alfatta** [comment]
Izin translate mas @mazipan 
Btw kalo td udah PR tinggal bikin branch baru base on branch itu atau fork ulang atau gimana ya mas?

**Comment by mazipan** [comment]
makanya PR nya jangan dari master harusnya, jadi cukup bikin branch baru

**Comment by mazipan** [comment]
Baca soal rebase git branch [https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase)

**Comment by alfatta** [comment]
PR nya dr branch options/dom mas td

**Comment by mazipan** [comment]
Branch masternya di perbarui dengan bikin PR ke master diri sendiri aja dulu.

**Comment by alfatta** [comment]
Oooh gituu
Sip mas berarti setelah PR ke master sendiri tinggal bikin branch baru dr situ kn ya

**Comment by alfatta** [comment]
Done in #155
