### ISSUE TITLE
[API] Options / Composition

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#108]

**Comment by Paskalouis** [comment]
Halo mas @mazipan , saya boleh ambil issue ini ?
Also mungkin boleh minta bantuan lokasi markdownnya.
Terima kasih.

**Comment by mazipan** [comment]
Markdown nya satu disini https://github.com/vuejs-id/docs/blob/master/src/v2/api/index.md

Cuma sectio nya ada banyak.
Cari section composition

**Comment by Paskalouis** [comment]
Halo2 mas @mazipan dan @mandaputtra .
PRnya sudah siap di review ya, minta tolong review.
Berikut PRnya: https://github.com/vuejs-id/docs/pull/177

Terima kasih.
