### ISSUE TITLE
Halaman Class and Style Bindings

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#11]

**Comment by gustialfian** [comment]
Saya nyoba ngerjain halaman ini mas @mazipan

**Comment by mazipan** [comment]
Silahkan mas, akan dikerjakan oleh mas @gustialfian

**Comment by mazipan** [comment]
Masih ngerjain ini kah mas @gustialfian ?

**Comment by gustialfian** [comment]
Iya mas besok mau pull request knp ya?

**Comment by gustialfian** [comment]
Kemarin saya sudah buat PR mas. bisa di review dulu.

**Comment by mazipan** [comment]
PR Open in #76
