### ISSUE TITLE
[API] Special Attributes

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#115]

**Comment by HikvIneH** [comment]
@mazipan halo, saya boleh di assign untuk yang ini?

**Comment by mandaputtra** [comment]
Okay mas, silahkan 😄

**Comment by mandaputtra** [comment]
Hallo mas @HikvIneH boleh sekalian Open Pull Request sambil nyicil di review

**Comment by frahmadani** [comment]
Halo mas @mandaputtra, untuk issue ini apa sudah closed, atau masih perlu perbaikan ya? Saya lihat di [sini](https://docs.vuejs.id/v2/api/#Atribut-Spesial) sebenarnya sudah diterjemahkan ya? Kalau masih perlu perbaikan, apa boleh saya di assign ke sini?

**Comment by mandaputtra** [comment]
@frahmadani monggo langsung di takeover saja ya mas.

**Comment by frahmadani** [comment]
Sudah selesai di-update ya mas, judul PR nya Update [API] - Special Attributes #180 . Mohon reviewnya, terima kasih.
