### ISSUE TITLE
[API] Built-In Components

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#116]

**Comment by iqbalaqaba** [comment]
@mazipan , halo permisi saya bisa assign kesini ?

**Comment by mandaputtra** [comment]
@iqbalaqaba ada progress untuk ini mas? bisa langsung buat PR untuk di review. Mengingat hacktoberfest seminggu lagi selesai.

**Comment by isatrio** [comment]
Belum ada jawaban kah? Boleh saya yang ambil?
