### ISSUE TITLE
[Cookbook] - Dockerize

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#144]
Original: https://github.com/vuejs-id/docs/blob/master/src/v2/cookbook/dockerize-vuejs-app.md

**Comment by ahmadrosid** [comment]
Hi mas @mazipan saya ambil kerjaan ini ya.

**Comment by mandaputtra** [comment]
Hi mas @ahmadrosid ada progress? mengingat hacktoberfest seminggu lagi akan selesai.

**Comment by mandaputtra** [comment]
Bagi yang ingin menyelesaikan hacktoberfest silahkan issue ini masih dibuka

**Comment by dummyeuy** [comment]
> Bagi yang ingin menyelesaikan hacktoberfest silahkan issue ini masih dibuka

Translasi/penerjemahan untuk docs/src/v2/cookbook/**dockerize-vuejs-app.md** ini boleh saya kerjakan?

@mazipan @mandaputtra

**Comment by mandaputtra** [comment]
@dummyeuy silahkan mas, ❤️

**Comment by dummyeuy** [comment]
Dear @mandaputtra @mazipan my latest commit as you can see on https://github.com/vuejs-id/docs/pull/188 is up.
Please kindly review it.

Thank you

**Comment by mandaputtra** [comment]
Closed by #188
