### ISSUE TITLE
[Cookbook] - Packaging SFC

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#147]
https://github.com/vuejs-id/docs/blob/master/src/v2/cookbook/packaging-sfc-for-npm.md

**Comment by elukuro** [comment]
mas @mazipan yang ini boleh saya bantu terjemahkan ?

**Comment by mandaputtra** [comment]
@elukuro hi mas ada progress? langsung PR saja mengingat hacktoberfest hampir berakhir seminggu lagi, nanti sambil di review

**Comment by elukuro** [comment]
@mandaputtra  Hi mas, maaf baru balas karena beberapa hari yang lalu sempat bedrest dan hari ini baru sehat kembali, saya usahakan weekend ini sudah selesai

**Comment by elukuro** [comment]
Hi @mandaputtra  berikut nomor pull request [184](https://github.com/vuejs-id/docs/pull/184) mohon di review terima kasih 😄
