### ISSUE TITLE
[Cookbook] - Axios

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#151]
https://github.com/vuejs-id/docs/blob/master/src/v2/cookbook/using-axios-to-consume-apis.md

**Comment by cahyonobagus** [comment]
@mazipan : saya boleh kontribusi untuk translate halaman ini ?

**Comment by cahyonobagus** [comment]
@mazipan : I submitted a [PR](https://github.com/vuejs-id/docs/pull/157). Please review it. Thank you.
