### ISSUE TITLE
Halaman Component Basics

### ISSUE THREAD

**Issue by nusendra** [vuejs-id/docs#16]

**Comment by iamyuu** [comment]
saya mau ambil yang ini, mas @nusendra @mazipan

**Comment by mazipan** [comment]
Siap silahkan mas @iamyuu

**Comment by mazipan** [comment]
Masih sanggup ngerjain ini gak mas @iamyuu? kalau gak sempet kita bisa minta temen lain buat ngerjain.

**Comment by iamyuu** [comment]
Maaf kalo terlalu lama, kemungkinan malam atau besok di push sekarang lagi di cek dulu

**Comment by mazipan** [comment]
PR open in #77
