### ISSUE TITLE
typo judul halaman index docs

### ISSUE THREAD

**Issue by almatins** [vuejs-id/docs#192]
di halaman index (/theme/layout/index.ejs), redaksi 'Kerangka Kerja **JavaSript**
nan Progresif', harusnya 'Kerangka Kerja **JavaScript**
nan Progresif'. bener typo ya?

**Comment by mandaputtra** [comment]
Iya mas, jika menemukan typo dan sebagainya silhakan langsung pull request mas. :+1:

**Comment by almatins** [comment]
@mandaputtra noted. thank you

**Comment by mazipan** [comment]
Fixed
