### ISSUE TITLE
Render Functions and JSX

### ISSUE THREAD

**Issue by nusendra** [vuejs-id/docs#27]

**Comment by iqbalaqaba** [comment]
Mas @nusendra & @mazipan , saya boleh di assign disini ? Thank you 😀

**Comment by mazipan** [comment]
Silakan mas @iqbalaqaba

**Comment by mazipan** [comment]
Ini gimana progressnya mas @iqbalaqaba?

**Comment by mazipan** [comment]
Dibuka lagi buat diterjemahkan oleh temen-temen lain ya...

**Comment by ravimahfunda** [comment]
Boleh saya di-assign disini mas @mazipan @nusendra , sama sebelum belum ada update sama skali ya ?

**Comment by mandaputtra** [comment]
Okay mas @ravimahfunda silahkan

**Comment by ravimahfunda** [comment]
nais, progress sekarang udah sampe sub DOM Virtual

**Comment by ravimahfunda** [comment]
@mandaputtra kang nanya dong, untuk komentar yg ada di bagian code perlu ditranslate juga gk ?

**Comment by nusendra** [comment]
perlu juga mas @ravimahfunda

**Comment by ravimahfunda** [comment]
oke siap laksanakan

**Comment by mazipan** [comment]
Bisa bikin PR dulu mas @ravimahfunda sambil jalan.
Biar bisa nyicil di review.

**Comment by ikrydev** [comment]
Hallo..
apakah @ravimahfunda  jadi ?

**Comment by ikrydev** [comment]
Kalau belum ada progress mungkin aku assign kesini boleh ? @mandaputtra @mazipan

**Comment by mandaputtra** [comment]
Langsung diambil saja mas mengingat sudah cukup lama @ikrydev

**Comment by ikrydev** [comment]
Baik Terima Kasih ^_^

**Comment by ikrydev** [comment]
maaf mas @mazipan  kok di close ya ?
ada yang belum padahal...

**Comment by mazipan** [comment]
Gapapa, open PR aja nanti
