### ISSUE TITLE
Halaman Routing

### ISSUE THREAD

**Issue by nusendra** [vuejs-id/docs#34]

**Comment by superpikar** [comment]
saya berminat translate ini mas @nusendra, belum diassign ke siapapun kan?

**Comment by mazipan** [comment]
Siap, reserved halaman ini akan dikerjakan oleh @superpikar.
Ditunggu pulll request nya mas.

**Comment by nusendra** [comment]
mantap mas @superpikar

**Comment by superpikar** [comment]
trims mas @mazipan @nusendra
