### ISSUE TITLE
Halaman Migrating from Vue 1.x

### ISSUE THREAD

**Issue by nusendra** [vuejs-id/docs#38]
https://github.com/vuejs-id/docs/blob/master/src/v2/guide/migration.md

- [x] FAQ -> #96 **MERGED**
- [x] Templates -> #96 **MERGED**
- [x] Props
- [x] Computed Properties
- [x] Built-in Directives
- [x] Custom Directives
- [x] Filters
- [x] Slots
- [x] Interpolation
- [x] DOM-Focused Instance Methods
- [x] Meta Instance Methods
- [x] Global Config

**Comment by wendyadi** [comment]
Halaman ini panjang sekali
Menurut saya ada bagusnya di-breakdown jadi bbrp task @nusendra @mazipan 
Jadi reviewnya juga gak setengah mati

Content migration.md:

- FAQ
- Templates
- Props
- Computed Properties
- Built-in Directives
- Custom Directives
- Filters
- Slots
- Interpolation
- DOM-Focused Instance Methods
- Meta Instance Methods
- Global Config

**Comment by mazipan** [comment]
Bisa PR sebagian2 aja mas @wendyadi

**Comment by wendyadi** [comment]
Okay saya take FAQ & Templates dlu ya @mazipan @nusendra

**Comment by nusendra** [comment]
Oke mas @wendyadi . Saya gas Props dan Computed Properties

**Comment by wendyadi** [comment]
Sorry agak lama, 
FAQ & templates di #96 ya

sembari direview saya ambil 
Built-in Directives dan Custom Directives okay?
@nusendra @mazipan

**Comment by mandaputtra** [comment]
Untuk lanjutanya saya teruskan disini yak #128 #130
