### ISSUE TITLE
Halaman The Vue Instance

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#8]

**Comment by iqbalaqaba** [comment]
Permisi mas @mazipan , ini blm ada yang ambil kan ? boleh saya assign untuk contribute translate pada bagian ini ? terimakasih

**Comment by nusendra** [comment]
Oke issue ini dikerjakan oleh mas @iqbalaqaba. Thanks

**Comment by iqbalaqaba** [comment]
Mas @nusendra , sudah saya buat pr nomor [#51](https://github.com/vuejs-id/docs/pull/51)
